os: osx
osx_image: xcode9.4
language: swift
script: xcodebuild clean test -workspace iOSMain/iOSMain.xcworkspace -scheme "CI" -sdk iphonesimulator -destination "platform=iOS Simulator,OS=11.4,name=iPhone 11" ONLY_ACTIVE_ARCH=NO CODE_SIGNING_REQUIRED=NO
