devices([
   "iPhone 8",
   "iPhone 11"
])

languages([
   "en-US",
])

scheme("HabbityMainUITests")

workspace("HabbityMain/HabbityMain.xcworkspace")

output_directory("./fastlane/screenshots")

clear_previous_screenshots(true)

# Arguments to pass to the app on launch. See https://docs.fastlane.tools/actions/snapshot/#launch-arguments
# launch_arguments(["-favColor red"])

# For more information about all available options run
# fastlane action snapshot
